FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Установка всех необходимых системных зависимостей для Chromium
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    libnss3 \
    libatk-bridge2.0-0 \
    libdrm2 \
    libxkbcommon0 \
    libgbm1 \
    libasound2 \
    libxshmfence1 \
    libcups2 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libpango-1.0-0 \
    libcairo2 \
    && rm -rf /var/lib/apt/lists/*
    

# Установка Playwright и браузеров
RUN pip install playwright==1.40.0
RUN playwright install chromium

COPY requirements-test.txt .
RUN pip install --upgrade pip && pip install -r requirements-test.txt

COPY . .
