[pytest]

testpaths = tests
addopts = 
    --alluredir=allure-results
    ; --clean-alluredir
    -v
    --tb=short

markers = 
    api: API tests
    ui: UI tests
    smoke: Smoke tests
    regression: Regression tests
    slow: Slow tests

htmlpath = reports/report.html

norecursedirs = .git venv
python_files = test_*.py *_test.py
python_classes = Test* *Test
python_functions = test_* *_test