import pytest
from playwright.sync_api import Page, expect

def test_news_edit_editor_user(page: Page, base_url: str, editor_user, admin_session):
    """Editor user can see news edit page"""
    import re
    page.goto(base_url)
    page.get_by_role("link", name="🔐 Войти").click()
    page.locator("#id_username").fill(editor_user["username"])
    page.locator("#id_password").fill(editor_user["password"])
    page.get_by_role("button", name="Войти").click()
    page.get_by_role("link", name="📰 Читать все новости").click()
    page.locator(".edit-news-btn").nth(0).click()
    expect(page).to_have_url(re.compile(rf"{base_url}news/\d+/edit/"))
    expect(page.locator(".container .edit-news-container h1")).to_contain_text("✏️ Редактировать новость")
    expect(page.locator('.form-group label[for="id_title"]')).to_contain_text("Заголовок новости")
    expect(page.locator("#id_title")).to_be_visible()
    expect(page.locator("#id_title")).not_to_be_empty()
    expect(page.locator('.form-group label[for="id_category"]')).to_contain_text("Категория")
    expect(page.locator("#id_category")).to_be_visible()
    expect(page.locator("#id_category")).not_to_be_empty()
    expect(page.locator('.form-group label[for="id_short_description"]')).to_contain_text("Краткое описание")
    expect(page.locator("#id_short_description")).to_be_visible()
    expect(page.locator("#id_short_description")).not_to_be_empty()
    expect(page.locator(".hint-text")).to_contain_text("Это описание будет отображаться в списке новостей")
    expect(page.locator(".current-image p")).to_contain_text("📸 Текущее изображение:")
    expect(page.get_by_role("checkbox", name="Удалить изображение")).to_be_visible()
    expect(page.locator('.form-group label[for="id_photo"]')).to_contain_text("Новое изображение (необязательно)")
    expect(page.locator("#id_photo")).to_be_visible()
    expect(page.locator('.form-group:has(label[for="id_photo"]) .char-counter')).to_contain_text("Поддерживаются форматы: JPG, PNG, GIF")
    expect(page.locator('.form-group label[for="id_content"]')).to_contain_text("Содержание")
    expect(page.locator("#id_content")).to_be_visible()
    expect(page.get_by_role("checkbox", name="Опубликовано")).to_be_visible()
    expect(page.get_by_role("button", name="💾 Сохранить изменения")).to_be_visible()
    expect(page.get_by_role("link", name="❌ Отмена")).to_be_visible()
def test_news_edit_admin_user(page: Page, base_url: str, admin_user):
    """Admin user cann see news edit page"""
    import re
    page.goto(base_url)
    page.get_by_role("link", name="🔐 Войти").click()
    page.locator("#id_username").fill(admin_user["username"])
    page.locator("#id_password").fill(admin_user["password"])
    page.get_by_role("button", name="Войти").click()
    page.get_by_role("link", name="📰 Читать все новости").click()
    page.locator(".edit-news-btn").nth(0).click()
    expect(page).to_have_url(re.compile(rf"{base_url}news/\d+/edit/"))
    expect(page.locator(".container .edit-news-container h1")).to_contain_text("✏️ Редактировать новость")
    expect(page.locator('.form-group label[for="id_title"]')).to_contain_text("Заголовок новости")
    expect(page.locator("#id_title")).to_be_visible()
    expect(page.locator("#id_title")).not_to_be_empty()
    expect(page.locator('.form-group label[for="id_category"]')).to_contain_text("Категория")
    expect(page.locator("#id_category")).to_be_visible()
    expect(page.locator("#id_category")).not_to_be_empty()
    expect(page.locator('.form-group label[for="id_short_description"]')).to_contain_text("Краткое описание")
    expect(page.locator("#id_short_description")).to_be_visible()
    expect(page.locator("#id_short_description")).not_to_be_empty()
    expect(page.locator(".hint-text")).to_contain_text("Это описание будет отображаться в списке новостей")
    expect(page.locator(".current-image p")).to_contain_text("📸 Текущее изображение:")
    expect(page.get_by_role("checkbox", name="Удалить изображение")).to_be_visible()
    expect(page.locator('.form-group label[for="id_photo"]')).to_contain_text("Новое изображение (необязательно)")
    expect(page.locator("#id_photo")).to_be_visible()
    expect(page.locator('.form-group:has(label[for="id_photo"]) .char-counter')).to_contain_text("Поддерживаются форматы: JPG, PNG, GIF")
    expect(page.locator('.form-group label[for="id_content"]')).to_contain_text("Содержание")
    expect(page.locator("#id_content")).to_be_visible()
    expect(page.get_by_role("checkbox", name="Опубликовано")).to_be_visible()
    expect(page.get_by_role("button", name="💾 Сохранить изменения")).to_be_visible()
    expect(page.get_by_role("link", name="❌ Отмена")).to_be_visible()
def test_news_edit_edition(page: Page, base_url: str, test_news, test_category, editor_user):
    """Editor user can edit news on news edit page"""
    page.goto(base_url)
    page.get_by_role("link", name="🔐 Войти").click()
    page.locator("#id_username").fill(editor_user["username"])
    page.locator("#id_password").fill(editor_user["password"])
    page.get_by_role("button", name="Войти").click()
    test_news_url = test_news["test_news_url"]
    page.goto(f"{test_news_url}edit/")
    page.locator("#id_title").fill("Changed title")
    page.locator("#id_category").select_option(test_category["test_category_id"])
    page.get_by_role("checkbox", name="Удалить изображение").click()
    page.locator("#id_content").fill("Changed content")
    page.get_by_role("checkbox", name="Опубликовано").click()
    page.get_by_role("button", name="💾 Сохранить изменения").click()
    expect(page).to_have_url(test_news_url)
    expect(page.locator(".news-detail-container .news-detail-title")).to_contain_text("Changed title")
    expect(page.locator(".news-detail-meta .category-badge")).to_contain_text(test_category["test_category_data"]["title"])
    expect(page.locator(".news-detail-content .news-detail-text")).to_contain_text("Changed content")
    expect(page.locator(".news-detail-content .news-detail-image")).not_to_be_visible()
def test_news_edit_canceling(page: Page, base_url: str, editor_user):
    """Editor user can cancel edition news on news edit page"""
    import re
    page.goto(base_url)
    page.get_by_role("link", name="🔐 Войти").click()
    page.locator("#id_username").fill(editor_user["username"])
    page.locator("#id_password").fill(editor_user["password"])
    page.get_by_role("button", name="Войти").click()
    page.get_by_role("link", name="📰 Читать все новости").click()
    page.locator(".edit-news-btn").nth(0).click()
    page.get_by_role("link", name="❌ Отмена").click()
    expect(page).to_have_url(re.compile(rf"{base_url}news/\d+/"))
def test_news_edit_empty_fields(page: Page, base_url: str, editor_user):
    """Editor user can't edit news to empty fields on news edit page"""
    import re
    page.goto(base_url)
    page.get_by_role("link", name="🔐 Войти").click()
    page.locator("#id_username").fill(editor_user["username"])
    page.locator("#id_password").fill(editor_user["password"])
    page.get_by_role("button", name="Войти").click()
    page.get_by_role("link", name="📰 Читать все новости").click()
    page.locator(".edit-news-btn").nth(0).click()
    page.locator("#id_title").fill("")
    page.locator("#id_category").select_option("")
    page.get_by_role("button", name="💾 Сохранить изменения").click()
    expect(page).to_have_url(re.compile(rf"{base_url}news/\d+/edit/"))
def test_news_edit_invalid_fields(page: Page, base_url: str, editor_user):
    """Edit user can't edit news to invalid fields on news edit page"""
    import re
    page.goto(base_url)
    page.get_by_role("link", name="🔐 Войти").click()
    page.locator("#id_username").fill(editor_user["username"])
    page.locator("#id_password").fill(editor_user["password"])
    page.get_by_role("button", name="Войти").click()
    page.get_by_role("link", name="📰 Читать все новости").click()
    page.locator(".edit-news-btn").nth(0).click()
    page.locator("#id_title").fill("1")
    page.get_by_role("button", name="💾 Сохранить изменения").click()
    expect(page).to_have_url(re.compile(rf"{base_url}news/\d+/edit/"))