name: API & UI Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - '.github/workflows/api-ui-tests.yml'
      - 'tests/api/**'      
      - 'tests/ui/**'       
      - 'tests/conftest.py' 
      - 'tests/helpers.py'
      - 'tests/test_data.py' 
      - 'tests/files_for_tests/**'
  workflow_dispatch: 

jobs:
  tests_api_ui:
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout Django Website
      uses: actions/checkout@v4
      with:
        repository: explrprobe-tech/my_django_news_website
        path: django-website

    - name: Checkout tests
      uses: actions/checkout@v4
      with:
        path: tests
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Django Website dependecies
      run: |
        cd django-website/mysite
        pip install -r requirements.txt

    - name: Validate Django Website
      run: |
        cd django-website/mysite
        python manage.py check

    - name: Check migration Django Website
      run: |
        cd django-website/mysite
        python manage.py makemigrations --check --dry-run

    - name: Run Django Website
      run: |
        cd django-website/mysite
        python manage.py runserver 0.0.0.0:8000 &

    - name: ⏳ Wait for Django to be ready
      run: |
        for i in {1..30}; do
          if curl -s http://127.0.0.1:8000/ > /dev/null; then
            echo "✅ Django is ready!"
            exit 0
          fi
          echo "Waiting for Django... ($i/30)"
          sleep 2
        done
        echo "❌ Django failed to start"
        exit 1

    - name: Install tests dependencies
      run: |
        cd tests
        pip install -r requirements-test.txt

    - name: 🔽 Install Playwright browsers
      run: |
        cd tests
        playwright install chromium

    - name: Run api tests
      run: |
        cd tests/tests
        pytest api/ -v
        
    - name: Run ui tests
      run: |
        cd tests/tests
        pytest ui/ -v
  
  load_tests:
    runs-on: ubuntu-latest
    if: github.event.inputs.test-type == 'load' || github.event.inputs.test-type == 'all'

    steps:
      - name: Checkout Django Website
        uses: actions/checkout@v4
        with:
          repository: explrprobe-tech/my_django_news_website
          path: django-website

      - name: Checkout tests
        uses: actions/checkout@v4
        with:
          path: tests

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Django dependencies
        run: |
          cd django-website/mysite
          pip install -r requirements.txt
          pip install gunicorn

      - name: Start DJango with Gunicorn
        run: |
          cd django-website/mysite
          gunicorn --workers 4 --bind 0.0.0.0:8000 mysite.wsgi:application &

      - name: Wait for Django
        run: |
          for i in {1..30}; do
            if curl -s http://127.0.0.1:8000/ > /dev/null; then
              echo "✅ Django is ready for load tests!"
              exit 0
            fi
            sleep 2
          done
          exit 1

      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Run smoke load test
        run: |
          cd tests/tests
          k6 run load_tests/smoke_test.js
        env:
          BASE_URL: http://localhost:8000
